language: node_js
node_js:
  - 6.6.x
env:
  - NODE_ENV=TEST
sudo: false
script:
  - npm run lint
  - npm run test:coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
